[package]
name = "actix_web_demo"
version = "0.0.0"
edition = "2024"

[dependencies]
# 使用工作空间管理的依赖
# Actix Web框架
actix-web = { workspace = true }
# 公共响应处理
common_wrapper = { path = "../common_wrapper" }
# 异步运行时
tokio = { workspace = true, features = ["full"] }